### ISSUE TITLE
Download link is invalid

### ISSUE THREAD

**Issue by robmoore** [timboudreau/tiny-maven-proxy#2]
Thanks for making this project available publicly!

I tried to download the JAR at the link provided in the README (http://timboudreau.com/builds/job/tiny-maven-proxy/lastSuccessfulBuild/artifact/target/tiny-maven-proxy.jar) but got a 404.

It appears a correct URL might be one of these?
- https://timboudreau.com/builds/job/tiny-maven-proxy/lastStableBuild/artifact/tiny-maven-proxy/target/tiny-maven-proxy.jar
- https://timboudreau.com/builds/job/tiny-maven-proxy/lastSuccessfulBuild/artifact/tiny-maven-proxy/target/tiny-maven-proxy.jar

**Comment by timboudreau** [comment]
Yeah, I think Jenkins changed the paths it serves stuff from.  I'll update
the link.

-Tim

**Comment by timboudreau** [comment]
Fixed
