### ISSUE TITLE
`urls` property does not appear to have any effect

### ISSUE THREAD

**Issue by robmoore** [timboudreau/tiny-maven-proxy#3]
I'm using a properties file and have used the `urls` property but I'm not seeing any difference in terms of the mirrored repos. The `port` property is working for me so I'm positive it's finding the properties file.

**Comment by timboudreau** [comment]
Hmm, and the properties file's _exact name_ is `tiny-maven-proxy.properties` and it is located in one of

 * `/etc`
 * `/opt/local/etc`
 * `~/` (your home dir)
 * `./` (the process working dir)

Hmm, this may be my bad with the docs - the property name is `mirror`, not `urls` (I think it was that early on in the project's life).  Apologies for not catching that.

**Comment by timboudreau** [comment]
And, docs are fixed.
